### ISSUE TITLE
Heroku Push Problems

### ISSUE THREAD

**Issue by SamMatthews9** [SamMatthews9/JavaScript-Motion-Activated-Midi#42]
Hey, I've been having a tough time pushing our app to Heroku.  All the HTML, CSS/Sass and JS functions load properly, but some of the files aren't linking properly.  Initially we had the audio files working when they were loaded directly to the local, but since they weren't on the internet, when I pushed them to Heroku none of the audio files loaded properly.  I tried using some different Heroku addons and gems, but I realized they weren't the right tools so I started to use S3 again. 

All of the audio files are in a bucket, and should be publicly accessible.  Here is an example of one of them: https://s3.amazonaws.com/project3sequencer/audio_files/marimba_7.mp3

I added those links directly to the seed file of each cell (in my current branch).  Again, the work on my local, but when I I try to push to Heroku I am getting a 404 loading error and it's not calling on the s3 public bucket but the same herokuapp/assets folder.  I'll attach an image below.  Could someone please help me out! Thanks! @harimohanraj89 @DrRobotmck @htella 

![screen shot 2015-01-05 at 4 04 04 pm](https://cloud.githubusercontent.com/assets/8835790/5620016/92514430-94f5-11e4-92fa-3926c149e231.png)

**Comment by harimohanraj89** [comment]
If you are using the `asset_path` helper, your web page will only look for the files in your Rails assets. In order to look for the file in your s3 bucket, you will either need to have your web page source its assets directly from https://s3.amazonaws.com/project3sequencer/audio_files/marimba_7.mp3, for example, or have your web page hit a particular route on your server, and have your server fetch the audio file for you. Since your audio appears to be public, thought, the former approach would work.

```
<audio id="marimba-7" src="https://s3.amazonaws.com/project3sequencer/audio_files/marimba_7.mp3"></audio>
```

**Comment by SamMatthews9** [comment]
When rendering all the cells onto the page (app.js) , I add the audio to
the div (for the button) like this: <code>
var purple_audio = $('<audio>').attr('id', 'purple_audio')
var purple_source = $('<source>').attr('src',
data.purple_note).attr('type', 'audio/mpeg'); </code>

The purple_note attribute for each cell is the s3 link in the seed.  I'm
not really sure how I would use that asset directly linked to the audio
tag, unless I manually put it in for each cell (outside of the seed file).
